// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// RMSE
double RMSE(NumericVector observation_x, NumericVector observation_y, NumericVector observation_values, double power);
RcppExport SEXP _IDW_RMSE(SEXP observation_xSEXP, SEXP observation_ySEXP, SEXP observation_valuesSEXP, SEXP powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type observation_x(observation_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type observation_y(observation_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type observation_values(observation_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type power(powerSEXP);
    rcpp_result_gen = Rcpp::wrap(RMSE(observation_x, observation_y, observation_values, power));
    return rcpp_result_gen;
END_RCPP
}
// run_IDW
NumericVector run_IDW(NumericVector interpolate_x, NumericVector interpolate_y, NumericVector observation_x, NumericVector observation_y, NumericVector observation_values, double power);
RcppExport SEXP _IDW_run_IDW(SEXP interpolate_xSEXP, SEXP interpolate_ySEXP, SEXP observation_xSEXP, SEXP observation_ySEXP, SEXP observation_valuesSEXP, SEXP powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type interpolate_x(interpolate_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type interpolate_y(interpolate_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type observation_x(observation_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type observation_y(observation_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type observation_values(observation_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type power(powerSEXP);
    rcpp_result_gen = Rcpp::wrap(run_IDW(interpolate_x, interpolate_y, observation_x, observation_y, observation_values, power));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IDW_RMSE", (DL_FUNC) &_IDW_RMSE, 4},
    {"_IDW_run_IDW", (DL_FUNC) &_IDW_run_IDW, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_IDW(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
