# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RMSE <- function(observation_x, observation_y, observation_values, power) {
    .Call(`_IDW_RMSE`, observation_x, observation_y, observation_values, power)
}

run_IDW <- function(interpolate_x, interpolate_y, observation_x, observation_y, observation_values, power) {
    .Call(`_IDW_run_IDW`, interpolate_x, interpolate_y, observation_x, observation_y, observation_values, power)
}

